### ISSUE TITLE
Add color support

### ISSUE THREAD

**Issue by hello-smile6** [hello-smile6/neofetch-js#10]
- [x] Figure out how to strip ANSI escape sequences
- [x] Update icons

@webdev03

**Comment by webdev03** [comment]
Hmm I'll see this later!

**Comment by hello-smile6** [comment]
> Hmm I'll see this later!

Have some ideas, I'll look into it and make a new branch for this

**Comment by hello-smile6** [comment]
@webdev03 https://github.com/chalk/strip-ansi

**Comment by hello-smile6** [comment]
Let's just rewrite it inline.
https://cdn.jsdelivr.net/npm/ansi-regex@6.0.1/index.js
Just run that as a function...

**Comment by hello-smile6** [comment]
Done!
